name: Test Code Quality

on:
  push:
    branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run tests
        steps:
            - uses: actions/checkout@v6
            - id: test-setup
              uses: ./.github/actions/python-setup
            - name: Run pytest
              run: pytest

    lint:
        runs-on: ubuntu-latest
        name: Run linter
        steps:
            - uses: actions/checkout@v6
            - id: lint-setup
              uses: ./.github/actions/python-setup
            - name: Run pylint
              run: pylint $(git ls-files '*.py')

    coverage:
        runs-on: ubuntu-latest
        name: Run coverage
        steps:
            - uses: actions/checkout@v6
            - id: coverage-setup
              uses: ./.github/actions/python-setup
            - name: Run coverage.py
              run: |
                  coverage run -m pytest
                  coverage report -m
