name: Test Code Quality

on:
  pull_request:
    branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        name: Run linter
        strategy:
          matrix:
            python-version: ["3.12"]
        steps:
            - uses: actions/checkout@v6
            - id: lint-setup
              uses: ./.github/actions/python-setup
            - name: Run pylint
              run: |
                cd django-rocket-request
                pylint .

    tests-and-coverage:
        runs-on: ${{ matrix.os }}
        name: Tests and coverage
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
            python-version: ["3.12", "3.13", "3.14"]
        steps:
            - uses: actions/checkout@v6
            - id: coverage-setup
              uses: ./.github/actions/python-setup
            - name: Run Django tests and coverage
              run: |
                  cd django-rocket-request
                  coverage run --source='.' manage.py test --exclude-tag selenium django_distribute
                  coverage report -m
                  coverage html
            - uses: actions/upload-artifact@v7
              with:
                name: coverage
                path: django-rocket-request/htmlcov
