name: Test Code Quality

on: [ push ]

jobs:
    test:
        runs-on: ubuntu-latest
        name: Run tests
        steps:
            - id: test-setup
              uses: ./.github/actions/python-setup
            - name: Run pytest
              run: pytest

    lint:
        runs-on: ubuntu-latest
        name: Run linter
        steps:
            - name: Run pylint
              run: pylint $(git ls-files '*.py')

    coverage:
        runs-on: ubuntu-latest
        name: Run coverage
        steps:
            - name: Run coverage.py
              run: |
                  coverage run -m pytest
                  coverage report -m
